[build]
  command = "npm ci || npm i"
  publish = "."
  functions = "netlify/functions"

# Environment variables
[build.environment]
  SECRETS_SCAN_OMIT_PATHS = "valiant-store-*.json"

# Proxy API requests to Netlify Function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Serve dashboard as the root page
[[redirects]]
  from = "/"
  to = "/dashboard.html"
  status = 200

# Allow all other static assets as-is
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
